"""Tests for QR code service."""

import tempfile
from pathlib import Path

import pytest

from staff_meal.models import Item, Order, OrderItem, OrderSource
from staff_meal.qr import decode_qr, generate_qr


class TestGenerateQR:
    """Tests for QR code generation."""

    def test_generate_qr_creates_image(self) -> None:
        """generate_qr creates a valid PIL Image."""
        order = Order(
            order_id="TEST-123",
            source=OrderSource.UBER_EATS,
            items=[OrderItem(item=Item.GYOZA, quantity=1)],
        )
        img = generate_qr(order)
        assert img is not None
        assert img.size[0] > 0
        assert img.size[1] > 0

    def test_generate_qr_saves_to_file(self) -> None:
        """generate_qr can save QR code to file."""
        order = Order(
            order_id="TEST-123",
            source=OrderSource.UBER_EATS,
            items=[OrderItem(item=Item.GYOZA, quantity=1)],
        )
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            output_path = tmp.name

        generate_qr(order, output_path)
        assert Path(output_path).exists()
        Path(output_path).unlink()

    def test_generate_qr_with_multiple_items(self) -> None:
        """generate_qr works with multiple items."""
        order = Order(
            order_id="TEST-456",
            source=OrderSource.DELIVEROO,
            items=[
                OrderItem(item=Item.GYOZA, quantity=2),
                OrderItem(item=Item.SAUCE, quantity=1),
            ],
        )
        img = generate_qr(order)
        assert img is not None


class TestDecodeQR:
    """Tests for QR code decoding."""

    def test_decode_qr_round_trip(self) -> None:
        """decode_qr can decode QR code generated by generate_qr."""
        order = Order(
            order_id="TEST-789",
            source=OrderSource.UBER_EATS,
            items=[
                OrderItem(item=Item.GYOZA, quantity=1),
                OrderItem(item=Item.MAKI_CALIFORNIA, quantity=2),
            ],
        )

        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            qr_path = tmp.name

        generate_qr(order, qr_path)
        decoded_order = decode_qr(qr_path)

        assert decoded_order.order_id == order.order_id
        assert decoded_order.source == order.source
        assert len(decoded_order.items) == len(order.items)
        assert decoded_order.items[0].item == order.items[0].item
        assert decoded_order.items[0].quantity == order.items[0].quantity
        assert decoded_order.items[1].item == order.items[1].item
        assert decoded_order.items[1].quantity == order.items[1].quantity

        Path(qr_path).unlink()

    def test_decode_qr_no_qr_code(self) -> None:
        """decode_qr raises ValueError for image without QR code."""
        from PIL import Image

        # Create a valid image without QR code
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            img = Image.new("RGB", (100, 100), color="white")
            img.save(tmp.name)
            no_qr_path = tmp.name

        with pytest.raises(ValueError, match="No QR code found"):
            decode_qr(no_qr_path)

        Path(no_qr_path).unlink()
